### ISSUE TITLE
composer-install redis/git ?

### ISSUE THREAD

**Issue by ghost** [md-systems/redis#11]
In the current state, prior to installable release on drupal.org/packagist, what's correct D8-friendly usage for composer-install from this git repo?

I've a composer-installed Drupal  8.0.3 & a variety of modules.

Now, i'd like to install md-systems/redis to starting working on.

1st

```
cd <drupal root>
```

then add this git repo locally

```
composer config repositories.md-systems git https://github.com/md-systems/redis.git
```

so that

```
cat <druapl root>/composer.json
    ...
      "repositories": {
        "md-systems": {
          "type": "git",
          "url": "https://github.com/md-systems/redis.git"
        }
      }
    ...
```

But attempt to

```
composer require md-systems/redis:dev-8.x-1.x
```

fails

```
Loading composer repositories with package information
Updating dependencies (including require-dev)                                         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package md-systems/redis could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

Is something missing from my method, or the pacakge?

**Comment by pounard** [comment]
Use type = "vcs" instead, that's what I do, but I usually give a git:// url instead, not sure that with https:// composer will find out by itself that your vcs is git, nevertheless you should try it

**Comment by Berdir** [comment]
It's drupal/redis, not md-systems/redis. The name of the repository is not relevant, only what's in the composer.json.

**Comment by ghost** [comment]
both corrections were required -- 'vcs' and 'drupal/redis'.  site is up & running with Redis. now to figure out helpful tests ...

thx.
