### ISSUE TITLE
Running drush cr does not clear Redis cache.

### ISSUE THREAD

**Issue by mroycroft** [md-systems/redis#16]
Hello,

I noticed that running drush cr does not clear or remove any keys from the Redis cache.

In the deleteAll function, located in src/Cache/PhpRedis.php, if I add in the line `$this->client->flushDB();`, it will then clear the Redis cache.

**Comment by Berdir** [comment]
I think that's a duplicate of https://github.com/md-systems/redis/issues/8

**Comment by Berdir** [comment]
Until that is resolved, just put a fixed $settings['cache_prefix'] in settings.php.
