### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by csandanov** [md-systems/redis#18]
It seems you have a typo when you describe how to set password, probably should be `$settings['redis.connection']['password'] = "mypassword";` instead of `$settings['redis.connection']['base'] = "mypassword";`

**Comment by Berdir** [comment]
Correct, please make a pull request. You can just edit the file directly in github and then it creates a pull request for you.

**Comment by csandanov** [comment]
#20

**Comment by csandanov** [comment]
See PR #20

**Comment by gido** [comment]
This issue can be closed since the PR is merged
